/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main(){
	int sum = 0;
	int prev = 0;
	int next = 1;
	int temp = 0;
	while(next < 4000000){
		temp = next;
		next = prev + next;
		prev = temp;
		if(next % 2 == 0)
			sum += next;
	}
	cout << sum << endl;
}